### ISSUE TITLE
[기능 요청] 캡슐화 그룹에도 이미지를 넣을수 있도록 요청 드립니다.

### ISSUE THREAD

**Issue by hi763** [vulcan9/jikji.editor#159]
**제안할 기능이 어떤 문제를 해결하기 위한 것인가요? 설명 부탁합니다.**
저희 캡슐화 작업을 하면 직지 화면에서도 보기의 내용을 바꿀수 있는데요
보기 내용에 이미지를 넣어야 하는 경우 이미지를 추가하고 이미지도 변경할 수 있으면 좋을  것 같습니다. 
단순히 보기에 텍스트만 넣는 것이 아니라, 이미지도 넣을 수 있으면 좋을 것 같습니다. 
(음원도 가능 하다면요)

**어떤식으로 문제가 해결됬으면 좋겠습니까?**
캡슐화 목록에서 이미지를 선택해서 직지 메인화면에서 수정하거나 이미지를 변경 할 수 있도록 하면 좋을 것 같습니다. 

**문제 해결할때 고려(주의) 해야할 다른 사항이 있을까요?**
1. 이미지 용량 및 사이즈에 관한 부분이 이슈가 있을 수 있을 것 같습니다.
2. 화면에 위치와 영역에 대한 부분이 고려 되어야 할것 같습니다. 

**그밖에 남기고 싶은 말**

**Comment by vulcan9** [comment]
Jik-ji_Editor_3.0.3 부터 로컬폴더 직접 접근 가능해짐
