### ISSUE TITLE
gif 이미지 실행 관련

### ISSUE THREAD

**Issue by hi763** [vulcan9/jikji.editor#160]
**제안할 기능이 어떤 문제를 해결하기 위한 것인가요? 설명 부탁합니다.**
이미지에 gif를 넣고 이벤트(클릭) 후에 gif가 실행 되도록 하는 기능
- gif를 한번 실행 후에는 해당 이미지를 재실행하면 기존 기록이 남아 움직임이 실행되지 않습니다.

**어떤식으로 문제가 해결됬으면 좋겠습니까?**
random함수를 사용하여 계속 다른 이름으로 gif 이미지를 로드하는 방식을 사용 하였습니다. 

**문제 해결할때 고려(주의) 해야할 다른 사항이 있을까요?**

**그밖에 남기고 싶은 말**

**Comment by vulcan9** [comment]
cache 이미지를 사용하기때문에 보이기/감추기 기능 또는 리로딩 할때 animation GIF 이미지가 재생되지 않는 현상이 발생하고 있습니다.
`cache 이미지 사용하지 않음` 옵션을 두어 자동으로 기능을 설정할 수 있도록 보완하겠습니다.

**Comment by vulcan9** [comment]
**0.10.1** 버전(이상)에서 처리(구현) 되었습니다.
