### ISSUE TITLE
[기능 개선] 편집창 폭맞춤 쪽맞춤 지원 요청

### ISSUE THREAD

**Issue by tovsoft** [vulcan9/jikji.editor#161]
편집 창에 폭맞춤과 쪽맞춤이 지원되었으면 합니다.

우측 하단의 페이지 보기 % 지정하는 메뉴 옆에, 폭맞춤과 쪽맞춤 옵션이 추가될 수 있는지 검토 부탁드립니다.

**Comment by vulcan9** [comment]
**0.10.2** 버전(이상)에서 처리(구현) 되었습니다.
