### ISSUE TITLE
[기능 개선] 텍스트 박스 내 일부 텍스트 스타일 지정

### ISSUE THREAD

**Issue by tovsoft** [vulcan9/jikji.editor#162]
현재 텍스트 박스 내에 입력한 텍스트 중
일부분만 선택하여 스타일을 지정할 수 없습니다.

텍스트 박스 내에 입력한 텍스트 중
일부를 드래그 블럭 지정하여, 텍스트 스타일을 지정할 수 있는 기능이
지원되었으면 합니다.

검토 부탁드립니다.

**Comment by vulcan9** [comment]
**0.10.7** 버전(이상)에서 처리(구현) 되었습니다.
