### ISSUE TITLE
[기능 개선 사항 우선순위 정리]

### ISSUE THREAD

**Issue by tovsoft** [vulcan9/jikji.editor#164]
리스트가 너무 많아서 우선순위 정리가 쉽지 않네요.

사용성을 높이거나 빨리 처리가 가능한 것부터 했으면 하는데요.
아래 순서였으면 하는데... 검토 의견 부탁드립니다.

1. 157번 이슈 : 사용자가 에셋이나 배경을 추가할 수 있는 기능
2. 52번 이슈 : 미디어 재설정 메뉴에서 current time 설정
3. 38번 이슈 : 비디오 poster 설정
4. 28번 이슈 / 162번 이슈 : 텍스트 속성 중 style, 정렬기능 / 텍스트 박스 내 일부 텍스트 스타일 지정

나머지 있는 이슈들은 제가 내용을 이해하지 못한 부분들이 있어서, 차후에 설명 부탁드립니다.
참고로 에셋과 배경 디자인 기획이 오늘 완료될 예정이며, 다음 주에는 수석님께 전달이 가능할 것으로 예상됩니다.

**Comment by vulcan9** [comment]
색깔이 들어가야하는 텍스트 한줄을 수정하는데 텍스트박스를 3개를 사용하는 걸 보았습니다.
#161 번 이슈를 먼저 하는것이 좋을듯하여 `Milestones 0.11`버전에 추가합니다.

나머지는 추후 다시검토하겠습니다.

**Comment by vulcan9** [comment]
#162 번 이슈 **0.11.0** 버전(이상)에서 처리(구현) 되었습니다.

**Comment by vulcan9** [comment]
`Milestones 0.13` 버전 이후 다시 우선순위 정리합니다.
