### ISSUE TITLE
텍스트 입력시 화면 스크롤 문제

### ISSUE THREAD

**Issue by onlyeye26** [vulcan9/jikji.editor#165]
**이슈 내용**
화면이 확대가 되어 있는 상태에서 텍스트박스를 넣고 텍스트 입력시 화면이 텍스트가 좌측 하단 끝에 오도록 이동을 합니다.
텍스트를 입력하는 도중에 발생을 하며, space를 누르면 정상적으로 돌아옵니다.
또한, shift나 home/end키를 누르면 전혀 다른 곳으로 스크롤이 이동합니다,

**재연 방법**
1. 용지보다 화면을 더 확대합니다.
2. 텍스트 박스를 삽입합니다.
3. 텍스트 입력, space, shift나 home/end를 모두 눌러봅니다.
4. 화면의 스크롤이 움직이는 것을 볼 수 있습니다.

**Screenshots**
![K-001](https://user-images.githubusercontent.com/20455074/63558331-8e4a4680-c587-11e9-9d05-d99e612e8658.png)

**실행 환경**
 - 0.10.1

**Comment by vulcan9** [comment]
**0.10.7** 버전(이상)에서 처리(구현) 되었습니다.
