### ISSUE TITLE
컴포넌트의 텍스트 레이어가 잠기는 현상

### ISSUE THREAD

**Issue by onlyeye26** [vulcan9/jikji.editor#167]
**이슈 내용**
컴포넌트 제작시 컴포넌트의 그룹 안에 텍스트들의 레이어가 잠기는 현상

**재연 방법**
1. tsContents_quiz_0820.jjc을 직지에 등록 후 사용
2. 레이어 창을 열어 접힌 부분을 모두 오픈

**예상 동작**
가장 하위 depth(4번째)에 있는 텍스트의 레이어가 모두 잠겨 있음

**Screenshots**
![K-001](https://user-images.githubusercontent.com/20455074/64137195-b82a2580-ce31-11e9-8fa2-375aee43fc02.png)

**Additional context**
해당 현상 해결을 위해 tsContents_quiz_0820.jjc을 요청해 주시면 드리도록 하겠습니다.

**Comment by vulcan9** [comment]
컴포넌트 Export 당시 텍스트의 레이어가 잠금상태였다면 그 상태 그대로 Export 되었기때문에 Import 후 사용할때에도 잠금상태로 표시되는 것으로 추정됩니다.
컴포넌트 Export, Import 동작을 테스트 해본 결과 임의로 잠금 설정이 진행되는 로직은 발견되지 않았습니다.
해당 문제가 계속된다면 이 이슈를 reopen하여 컴포넌트 Export하는 상황을 재연할수 있도록 코멘트 부탁드립니다.
