### ISSUE TITLE
[기능 개선] 창크기를 줄였을 때 메뉴가 나오지 않는 현상

### ISSUE THREAD

**Issue by onlyeye26** [vulcan9/jikji.editor#168]
직지의 창 크기를 줄일 경우 특정 사이즈부터(가로 약1290px) 상단의 메뉴가 사라져 보이지 않는 현상이 있습니다.
우측 버튼들부터 가려져서 보이지 않습니다.
![K-002](https://user-images.githubusercontent.com/20455074/64137653-90888c80-ce34-11e9-9848-39b1d0bdd93a.png)

창 크기가 줄어들어 상단 버튼 일부의 노출이 불가할 경우 더보기를 사용하여 가려질 경우에도 버튼 사용이 가능하도록 해야할 것 같습니다.

또한, 창의 가로 크기를 더 줄일 경우 직지 사용의 제한이 됩니다.
![K-003](https://user-images.githubusercontent.com/20455074/64137813-4522ae00-ce35-11e9-913d-80a63ef3ef72.png)

위의 사진처럼 줄어드는 경우 사용이 어렵습니다. 따라서 일정 크기 이하로는 창 크기 조정이 되지 않도록 해야할 것 같습니다.

해당 사항에 대한 추가 내용이 필요하시면 말씀 부탁드립니다.

**Comment by vulcan9** [comment]
직지는 노트북 해상도와 직지에서 편집 작업에 필요한 해상도를 고려하여 1280x768 창 크기로 처음 실행됩니다.
직지의 모든 화면은 1280x768 사이즈 이하 사이즈에 대해서는 레이아웃이 고려되지 않았습니다.
1280x768 사이즈 이하에서 작업하는 상황이 있을지와 굳이 리사이징을 막을 필요가 있을까에 대한 고민 결과 창크기 최소 사이즈는 (개발시 편리성을 위해) 이보다 작게 리사이징 할수 있게 설정되어 배포되고 있습니다.
리사이징 제한이 필요하다고 판단되면 코멘트로 남겨주시기 바랍니다. 1280x768 사이즈로 최소 사이즈를 지정할 수 있습니다.

**Comment by vulcan9** [comment]
## Jik-ji_0.14.1
* 창 최소 크기를 1280x768 로 수정함
