### ISSUE TITLE
[기능개선] 비활성화된 버튼 마우스 오버시 버튼명 노출 요청

### ISSUE THREAD

**Issue by onlyeye26** [vulcan9/jikji.editor#169]
현재 활성화된 버튼에 마우스 오버시 버튼명이 제시가 되고 툴팁으로도 버튼명이 나오고 있습니다.
그러나 비활성화된 버튼의 경우에는 아무 동작이 없어 어떤 버튼인지 알 수가 없는 경우가 있습니다.
따라서 비활성화된 버튼에도 마우스 오버 하면 버튼명이 노출될 수 있도록 수정이 필요합니다.
![K-005](https://user-images.githubusercontent.com/20455074/64138005-faedfc80-ce35-11e9-9402-d555ca03e714.png)

**Comment by vulcan9** [comment]
## Jik-ji_0.11.6
* (#169 fixed) 비활성화된 버튼 마우스 오버시 버튼명 노출 요청 기능개선
