### ISSUE TITLE
[기능개선] 상단 메뉴 카테고리별 구분 텍스트 추가

### ISSUE THREAD

**Issue by onlyeye26** [vulcan9/jikji.editor#170]
현재 상단 메뉴는 기능별로 묶여서 구분이 되어 있습니다.
그러나 구분선이 잘 보이지 않고, 어떤 카테고리인지 직관성이 떨어집니다.
그래서 아래와 같이 최대한 영역을 덜 차지하도록 하되 카테고리명을 넣어서 사용자가 쉽게 알아볼 수 있도록 개선 요청드립니다.
![그림2](https://user-images.githubusercontent.com/20455074/64138087-502a0e00-ce36-11e9-94fb-511f04819460.png)

**Comment by vulcan9** [comment]
## Jik-ji_0.11.6
* (#170 fixed) 상단 메뉴 카테고리별 구분 텍스트 추가 기능개선
