### ISSUE TITLE
Binder(exe) 출판시 node_modules가 생성되지 않는 문제

### ISSUE THREAD

**Issue by onlyeye26** [vulcan9/jikji.editor#172]
**이슈 내용**
출판 옵션을 Jik-Ji Binder (exe)로 선택하여 출판시 app/node_modules 폴더가 없어서 실행에러가 발생함

**재연 방법**
1. 출판 옵션 선택 : Jik-Ji Binder (exe)
2. 출판
3. launcher.exe 실행
4. 실행 에러

**예상 동작**
콘텐츠 로딩바가 뜨고 그 후 동작이 없음

**Screenshots**
![K-001](https://user-images.githubusercontent.com/20455074/65291223-5685ed00-db8d-11e9-9ea8-1aa7604a00c0.png)

**Comment by vulcan9** [comment]
배포된 Jik-ji-Binder_0.5.9_cdbook_cd_appid 번들 파일중 node_modules 폴더가 누락되어  있는것이 확인되었습니다.  
누락된 파일들의 영향으로 출판 과정에 해당 파일들이 패키징되지 않았고 결과물이 정상동작되지 않았습니다.

## Jik-ji_0.11.4
* node_modules 폴더를 추가하였습니다.
