### ISSUE TITLE
텍스트 박스에서 텍스트 내용 편집

### ISSUE THREAD

**Issue by hi763** [vulcan9/jikji.editor#175]
**이슈 내용**
컴퍼넌트에 포함된 텍스트 상자의 내용을 편집할 경우
1. ① 텍스틀 박스를 더블 클릭하여 직접 박스안에서 내용을 편집
2. ② 우측의 편집창에서 수정
위와 같은 방법으로 수정을 할 수 있는데, ①에서 수정을 할 경우 반영이 되지 않는 현상

**재연 방법**
재연 방법을 단계별로 기술합니다.
1. 텍스트가 있는 컴포넌트를 불옵니다.
2. 텍스트 상자를 더블 클릭해서 안에 내용을 변경 합니다(1회)
3. 1회 동작시에는 내용이 반영되지 않습니다.
4. 텍스트 상자에서 다시 나왔다가 수정을 작성 하면 (2회) 이후에는 반영이 됩니다. 

**예상 동작**
①번에서 수정을 해도(1회 최조 시도 상황에서도) ②에 바로 수정 내용이 반영되어야 합니다.

**Screenshots**
![image](https://user-images.githubusercontent.com/23732865/66531690-95351480-eb47-11e9-9a0f-ab4b482b8ca0.png)

**실행 환경**

**Additional context**
기타 추가로 남기고 싶은 내용을 적어주세요

**Comment by vulcan9** [comment]
## Jik-ji_0.12.1
* (#175 fixed) 텍스트박스 편집내용 적용안되는 현상 수정
  - 더블클릭으로 편집모드로 들어간 후 한번 편집모드를 빠져나온 다음부터 속성창에 바인딩이 적용되는 것을 확인하였습니다.
  - 편집모드로 진입할때 context 초기화 시점이 잘못되어 이를 수정하였습니다.
