### ISSUE TITLE
[기능 요청] 기존 텍스트 박스 입력 형태 유지

### ISSUE THREAD

**Issue by hi763** [vulcan9/jikji.editor#178]
**제안할 기능이 어떤 문제를 해결하기 위한 것인가요? 설명 부탁합니다.**
기존 텍스트 박스의 경우 html 코드를 입력하지 않고 스페이스바와 엔터키로 위치를 잡았습니다. 
그런데 직지가 버전업 되면서 해당 부분이 html코드가 없으니 전부 한줄로 나옵니다.

**어떤식으로 문제가 해결됬으면 좋겠습니까?**
기존 텍스트 박스 입력 형태를 유지 했으면 좋겠습니다. 

**문제 해결할때 고려(주의) 해야할 다른 사항이 있을까요?**
html코드도 새버전에는 필요할것 같습니다. 향후에는 코드 입력 형태로 할것 같지만 잊전 버전에서 작업한 경우는 그 형태를 유지햇으면 좋겠습니다. 

**그밖에 남기고 싶은 말**
혹시 미래엔 업데이트 일정 때문에 먼저 요청 가능할까요?

**Comment by vulcan9** [comment]
`스타일 지정 가능한 텍스트박스` 옵션을 두어 기존 사용하던 텍스트박스와 구별하여 사용할 수 있도록 할 예정입니다.

### 비교
이전 텍스트박스와 스타일 기능이 추가된 텍스트 박스는 기능상 다음 차이점이 있습니다.

| 기능            | 이전 텍스트박스                 | 스타일 기능이 추가된 텍스트 박스 |
|:-------------:|------------------------------|----------------------------------------|
| 공백문자     | 띄어쓰기 그대로 적용됨 | 공백문자만(`&nbsp;`) 띄어쓰기로 인식함 |
|줄바꿈          | 줄바꿈(`enter`) 그대로 적용됨 | 줄바꿈 태그만 인식함 (`br, p, div...`) |
|줄높이(행간) | (관련 없음)                        | 태그로 감싸여져 있는 텍스트에만 적용됨 |
|스타일           | (관련 없음)                        | 태그로 감싸여져 있는 텍스트에만 적용됨 |

작업이 완료되는대로 패치버전을 우선 배포하도록 하겠습니다.

**Comment by vulcan9** [comment]
## Jik-ji_0.12.3
*  rich text box 하위버전 호환문제 해결
