### ISSUE TITLE
최초 라이선스 인증시 약관 동의 추가 요청

### ISSUE THREAD

**Issue by onlyeye26** [vulcan9/jikji.editor#179]
최초 라이선스 인증시 개인정보(이름, 이메일, 전화번호)를 수집하기 때문에 관련 약관 동의 처리가 필요합니다.
해당 기획서는 수정하실때에 말씀해 주시면 전달해 드리겠습니다.

**Comment by vulcan9** [comment]
## Jik-ji_0.13.0
* 최초 라이선스 인증시 약관 동의 추가
