### ISSUE TITLE
[기능요청] 미디어 파일을 재생시 로드할 수 있도록 수정 요청

### ISSUE THREAD

**Issue by onlyeye26** [vulcan9/jikji.editor#180]
** 현상
현재 직지 저작도구에서 미디어 파일(mp3, mp4 등)을 넣게 되면 브라우저에서 해당 페이지가 뜰 때에 다운로드 받도록(auto) 되어 있습니다. 이로 인해 미디어 파일이 많은 파일을 웹에서 사용시 페이지가 뜨는 속도가 크게 느려지고 있는 현상이 있습니다.

**해결방안
사용자가 미디어 파일을 넣을 때에 preload 하지 않도록 설정해주는 옵션이 있어 이를 선택시 미디어가 재생이 될 때 다운로드 받도록 수정이 필요합니다.

**Comment by vulcan9** [comment]
- 단위 테스트 결과 미디어 `preload` 옵션과 페이지 뜨는 속도(지연시간)과의 상관관계는 없는 것으로 생각됩니다.
- 하지만 필요한 기능이므로 Milestone에 해당 기능을 추가하는 일정을 고려하도록 하겠습니다.

**Comment by vulcan9** [comment]
페이지 로딩이 지연되는 원인 에 대하여는 #181 내용 참고
