### ISSUE TITLE
[기능요청] 라이선스 인증시 mac address가 여러개 등록될 수 있도록 수정 요청

### ISSUE THREAD

**Issue by onlyeye26** [vulcan9/jikji.editor#182]
**현상**
노트북에서 사용시 무선과 유선일 때에 mac address가 각각 다른 값으로 전송이 되어 인증에 실패함

**수정 요청**
라이선스 인증시(최초 설치시, 실행시) 전송 가능한 mac address를 모두 서버에 전송
현재 라이선스 관리자에는 mac address가 여러 개 올 때에 콤마(,)로 등록되도록 수정 완료

**특이사항**
현 상태(라이선스 관리자만 수정된 상태)에서 테스트 결과 : 테스트에 사용한 라이선스는 총 2copy
1. 유선으로 라이선스 등록
2. AppData에서 인증정보(FirstRun폴더) 삭제
3. 무선으로 라이선스 등록 (유선으로 등록한 정보는 유지)
4. 유선과 무선 모두 인증 성공

**Comment by vulcan9** [comment]
## Jik-ji_0.14.2
* 라이선스 인증시 mac address가 여러개 등록될 수 있도록 수정
  - 여러개의 MAC 주소를 등록하려면 쉼표(,)로 구분된 MAC 주소의 문자열 전송
