### ISSUE TITLE
[기능 요청] 이북에서 다른 이북 오픈시 다른 뷰어 호출 기능 추가 요청

### ISSUE THREAD

**Issue by onlyeye26** [vulcan9/jikji.editor#183]
**현상**
현재 직지에 있는 액션 중 '[link] 전자책(epub) 컨텐츠 열기'를 사용하면 이북에서 또 다른 이북을 열 수 있습니다. 그런데 이때 같은 뷰어를 사용하여 열립니다.
이전에 UI 콘텐츠 연결을 위해 임시로 바인더에 기능을 추가해 주셨는데요, 그때 테스트를 위해 아래와 같은 스크립트를 추가해서 사용할 수 있게 했습니다.
jj.link.ebook(epub 경로, 설정값, 뷰어 경로)

**요청 사항**
위에 임시로 만들었던 API를 직지 최신 버전에서 사용할 수 있도록 적용 부탁드립니다.

**Comment by vulcan9** [comment]
### Jik-ji_0.14.7
* 바인더 업데이트 적용 : Jik-ji-Binder_0.6.0

### Jik-ji-Binder_0.6.0
* viewer 경로 지정 가능하도록 linker api에 옵션 추가.
* download 팝업창 UI 변경 가능하도록 경로 지정 옵션 추가.
