### ISSUE TITLE
[수정요청] 통권/분권 구조로 이북 이동시 이슈

### ISSUE THREAD

**Issue by onlyeye26** [vulcan9/jikji.editor#184]
**이슈 내용**
뷰어 간 이동 콘텐츠에서 통권 - 분권간 이동에서 이슈가 발생

**샘플 제작**
1. ebook과 contents를 각각 직지로 제작
2. ebook은 통권 구조(-3페이지), contents는 분권(epub)으로 제작
3. ebook -> contents 이동시 아래 함수 사용
![K-001](https://user-images.githubusercontent.com/20455074/76814623-9547e780-683e-11ea-8e52-2a982675ffe4.png)
4. contents -> ebook 이동시 아래 함수 사용
![K-002](https://user-images.githubusercontent.com/20455074/76814647-a09b1300-683e-11ea-9337-fbcf7924663c.png)

**테스트 결과**
서버에 올려서 웹에서 확인시 문제 없음
그러나 바인더 로컬(exe)에서 실행시 ebook에서 contents를 열때 아래 창이 노출되며 오류 발생
![K-003](https://user-images.githubusercontent.com/20455074/76814808-20c17880-683f-11ea-904b-35a6f9b08088.png)
* 바인더 로컬에서 최초에 ebook인 통권을 열기 위해서 app/resourced에서 index.html을 아래와 같이 수정함
window.jj.link.ebook('./ebook/?page=-3', '_self')
-> window.jj.link.ebook('./ebook/?page=-3&bookBinding=true', '_self')

**수정 요청**
ebook과 contents는 각각 통권/분권 구조로 작업이 될 수 있습니다.
따라서 통권-분권(or 분권-통권)간 이동이 로컬과 웹에서 동일하게 동작해야 합니다.
* 제작한 샘플 파일은 필요시 전달해 드리도록 하겠습니다.

**Comment by vulcan9** [comment]
[jik-ji Binder 이슈 #63 ]( https://github.com/vulcan9/jik-ji-Binder/issues/63)로 이동합니다.

**Comment by vulcan9** [comment]
**jik-ji Binder 0.6.1** 버전에서 해결되었습니다.
**jikji.editor 0.15** 버전에서 **jik-ji Binder 0.6.1** 버전으로 업데이트 됩니다.
