### ISSUE TITLE
[검토 요청] 저작도구에서 출판시 단면/양면 선택 기능

### ISSUE THREAD

**Issue by onlyeye26** [vulcan9/jikji.editor#185]
**제안할 기능이 어떤 문제를 해결하기 위한 것인가요? 설명 부탁합니다.**
전자저작물 구조에서 뷰어간 이동을 통해 ebook과 contents를 연결하여 두 콘텐츠 모두 직지로 제작하고자 하는 의도를 가지고 있습니다. 그런데 보통 ebook은 양면, contents는 단면인 경우가 많습니다. 현재는 출판하게 되면 기본적으로 양면으로 나오게 되어 있어, contents의 경우에는 단면용 뷰어를 따로 세팅을 해줘야 합니다.

**어떤식으로 문제가 해결됬으면 좋겠습니까?**
직지 저작도구에서 출판할때 단면/양면을 선택할 수 있는 옵션이 있으면 좋을거 같습니다.

**문제 해결할때 고려(주의) 해야할 다른 사항이 있을까요?**
현재 사용중인 뷰어(이수석님 뷰어)는 config.js에 단면/양면을 설정하는 코드가 있습니다.
그리고 현재 개발중인 뷰어와 연동이 필요할 것 같습니다.

**Comment by vulcan9** [comment]
저작도구에 Book 설정 관련 도구가 있으면 좋겠네요.
확인된 사항
* 저작도구에 들어가 있는 뷰어는 버전이 불명확한 소스입니다. 저작도구 뷰어를 먼저 교체해야합니다.
* url 에서 parameter를 전달하여 옵션을 설정하도록 구현한 흔적은 있으나 현재 동작하지 않는것 같습니다. `contentInformationType` 같은 변수들에 따라 내부적으로 설정값이 강제 지정(하드코딩)되는것 같습니다.

뷰어에서 설정 관련 부분을 먼저 API로 정리한 후 저작도구에서 설정 관련 도구를 만들어 적용시켜주면 될것 같습니다.

**Comment by vulcan9** [comment]
**3.1.9** 버전(이상)에서 처리(구현) 되었습니다.

* 뷰어 옵션창 추가함
* 뷰어 설정 파일 적용
  - ebook 소스에 뷰어 설정 파일을 추가로 포함시킴
