### ISSUE TITLE
[기능 요청] 웹버전 연결시 입력 주소 간소화 방안 요청

### ISSUE THREAD

**Issue by onlyeye26** [vulcan9/jikji.editor#186]
**제안할 기능이 어떤 문제를 해결하기 위한 것인가요? 설명 부탁합니다.**
현재 웹버전을 출판하여 서버에 올려서 볼 때에 써야 하는 주소가 굉장히 깁니다.
예를 들면 아래와 같습니다.
http://116.120.58.79/web/sales/test/test/viewer/ebook/index.html?contentInformationURL=/web/sales/test/test/resource/ebook/&page=-3&bookBinding=true

**어떤식으로 문제가 해결됬으면 좋겠습니까?**
특정 경로에 HTML 파일(ex. index.html)을 하나 만들어 해당 경로로 접근시 이북이 열릴 수 있도록 하면 좋을 것 같습니다.
ex. http://116.120.58.79/web/sales/test/index.html

**Comment by vulcan9** [comment]
Binder Web 버전으로 출판했을때만 index 파일이 root 폴더에 없어 실행파일 찾는데 어려움이 있을것 같긴 합니다.
원래 의도는 `resource` 폴더 외에는 사용자가 파일을 변경하면 안되기 때문에 `resource` 폴더 안으로 파일을 넣어 두었습니다.

그리고, 출판할때 구조에 따르면 위와같이 뷰어의 index를 호출하는 것이 아니라 다음과 같이 resource 폴더의 index를 호출합니다.
```
http://~/web/sales/test/test/resource/index.html
```
Binder web 출판시 다음과 같은 index 파일을 함께 출판되도록 할 수도 있습니다.
**index.html**
```html
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Jik-ji-Binder for Web Epub Launcher</title>
    <link rel="shortcut icon" type="image/png" href="./resource/favicon.ico">

    <script src="./js/jquery.min.js"></script>
    <script src="./js/binder_web.min.js"></script>
</head>

<body>
<script>
    (function(){
        if(window.jj){
            // resource index 호출
	    window.jj.link.html('./resource/', '_self');
        }
    })()
</script>

</body>
</html>
```

**Comment by vulcan9** [comment]
**Jik-ji_2.0.0** 버전(이상)에서 처리(구현) 되었습니다.
