### ISSUE TITLE
직지 실행후 문서 제목 선택한 다음 동작하지 않는 현상

### ISSUE THREAD

**Issue by onlyeye26** [vulcan9/jikji.editor#187]
**이슈 내용**
직지 실행 후 좌측 상단의 화살표(썸네일창 보이기/숨기기) 클릭 후 '제목 없음'을 클릭하게 되면 출판정보 설정이 나오면서 이후 동작하지 않는 현상

**재연 방법**
1. 좌측 상단 화살표 클릭
![K-003](https://user-images.githubusercontent.com/20455074/78088785-310d5200-7400-11ea-99d8-6afa54f0375f.png)

2. 제목 없음 클릭
![K-004](https://user-images.githubusercontent.com/20455074/78088798-3bc7e700-7400-11ea-80d5-750aac40fa6e.png)

3. 이후 동작하지 않음

**실행 환경**
0.14.13에서 발견했습니다.

**Comment by vulcan9** [comment]
## Jik-ji_0.15.3
(fixed #187) 직지 실행후 문서 제목 선택한 다음 동작하지 않는 현상
  - 프로젝트가 생성되지 않은 경우일때 비활성화 시킴
