### ISSUE TITLE
버전 업데이트 이후 라이선스 인증 문제

### ISSUE THREAD

**Issue by onlyeye26** [vulcan9/jikji.editor#200]
**이슈 내용**
직지 업데이트 버전을 다운로드 후 실행시 라이선스 인증을 다시 해야 하는 문제가 있습니다.

**재연 방법**
(이전 버전의 직지는 이미 인증한 상태)
1. 직지 저작도구 업데이트 버전 다운로드
2. 라이선스 인증 창이 뜸

**재연 결과**
1. 1 copy 라이선스일 때
  - 동일한 라이선스 사용해도 디바이스 초과가 됨
  - 동일한 개인정보를 사용해도 동일
2. 2 copy 라이선스일 때 (1copy만 사용중)
  - 동일한 라이선스 사용하면 인증 성공
  - 라이선스 관리자 상에서는 동일한 mac address에 개인정보만 갱신됨
3. 2 copy 라이선스일 때 (2copy 모두 사용중)
  - 1번과 동일하게 디바이스 초과

**예상하는 정상 결과**
버전 업데이트 후 최신 버전 실행시 다시 라이선스를 묻지 않고 실행이 되어야 합니다.

**테스트용 라이선스**
테스트를 위한 라이선스는 2020-0406-CM97-X95B-C570 입니다.
현재 1 copy로 설정이 되어 있습니다.

**Comment by vulcan9** [comment]
## 원인
같은 mac 주소를 전송했을때 라이센스 관리 서버로부터 받은 응답입니다.
(copy 수만큼 이미 등록이 되어있는 상황일때)
```
# statusCode :  200
# response :  {"code":"63","message":"no space to add mac"}
```

## 해결 방안
라이센스 관리 서버에서 동일한 mac 주소에 대해서 등록하려고 할 경우에는 허용 응답을 보내주도록 수정해야할것 같습니다.

**Comment by onlyeye26** [comment]
위 사항을 적용하더라도 사용자가 새 버전을 다운로드 하여 업데이트시 라이선스 인증을 다시 받아야 하는 상황으로 이해가 됩니다.
새버전을 받더라도 사용자가 다시 인증을 하는 경우를 없애기 위해 아래 사항이 가능한지 검토 부탁드립니다.
1. 새버전 설치 후 실행시 이전 버전의 라이선스 및 기타 정보를 가져올 수 있을까요?
2. 위 사항이 안되면 혹시 레지스트리를 이용하면 문제가 될까요?

**Comment by vulcan9** [comment]
#### 이전 버전 라이센스
설치 버전이 많으면 가져올 라이센스를 선택해야함.

#### 레지스트리.
- 레지스트리를 이용 할수 있음. 
- 레지스트리를 이용해도 1번과 같은 경우 똑같이 발생함
- uninstall이 없으므로 등록된 레지스트리는 삭제할 수 없음
- 굳이 레지스트리를 사용?

#### 참고 
- 보통 라이센스 관리되는 프로그램들은 재설치시 무조건 라이센스 확인함.  
- 아니면 라이센스를 바꾸는 UI를 추가해서 배포해야 다음 문제가 안생길것 같음.
  + 등록한 라이센스가 여러개일때 라이센스 선택
  +  라이센스 삭제 시점, 
  + 등록된(사용하던)  라이센스를 바꿔야 할때

**Comment by onlyeye26** [comment]
서버에서 mac 주소와 라이선스가 동일하게 보낼때 허용 응답을 보내도록 수정 및 확인 완료
