### ISSUE TITLE
exe 실행시 nw.js 창이 뜨는 문제

### ISSUE THREAD

**Issue by onlyeye26** [vulcan9/jikji.editor#201]
**이슈 내용**
직지 저작도구 실행시 일부 PC에서 간혹 nw.js 창이 뜹니다. 
작업관리자에서 직지 관련 프로그램 종료 후에도 동일하고, appdata에서 폴더를 삭제해도 동일합니다.
다만, 더 상위 버전이 존재할 경우 해당 파일을 따로 받아서 사용하면 정상적으로 실행되었습니다.

**재연 방법**
1. 직지 exe 실행
2. nw,js 창이 뜸

**Screenshots**
![20200406_103224_397](https://user-images.githubusercontent.com/20455074/78516748-a3fa3c80-77f5-11ea-97c9-7bef80465f15.jpg)

**Additional context**
해당 현상이 나오는 PC가 필요하시다면, 현상이 재발생시 말씀드리겠습니다.

**Comment by vulcan9** [comment]
## 현상 설명
해당 현상은 배포 버전 폴더에 (`jik-ji.exe`와 같은 폴더) `package.json` 파일이 없을때 뜨는 창입니다.
이 현상은 설치를 마친 후 다시 시작할때 어떤 이유에 의해서 `package.json` 파일이 삭제 또는 생성되지 않은 경우입니다.

## 문제 원인
예상하기로는 특정 윈도우에서의 권한 또는 lock 현상 때문일것으로 생각되나 확실치는 않습니다. 
실행시 이 파일이 (임시로) 삭제되더라도 다시 생성되도록 되어 있지만 정상적으로 동작하지 않는것 같습니다.

## 문제 해결
이런 현상이 발생했을때는 다음과 같이 복구할 수 있습니다.

1. `[배포 버전 폴더]/launcher/package_backup.json` 파일을 복사합니다.
2. `[배포 버전 폴더]/package.json` 위치에 붙여넣기 합니다. (이름 변경)
3. `jik-ji.exe`를 다시 실행합니다.

**Comment by vulcan9** [comment]
로직상 문제점을 발견하지 못해 방어 코드를 추가하였습니다.  
문제 발생시 코멘트 부탁합니다.

## Jik-ji_0.15.4
* (fixed #201) exe 실행시 nw.js 창이 뜨는 문제
  - uncaughtException 발생시 자동으로 package.json 파일 자동 복구 로직 추가

**Comment by onlyeye26** [comment]
해당 이슈는 열려 있는 상태에서 현상이 지속적으로 발생하지 않는다는 판단이 될 때 닫도록 하겠습니다.

**Comment by onlyeye26** [comment]
최근 해당 현상이 발생하지 않았어서 이슈를 종료합니다.
