### ISSUE TITLE
라이선스 인증시 이슈

### ISSUE THREAD

**Issue by onlyeye26** [vulcan9/jikji.editor#206]
**이슈 내용**
특정 PC의 무선 연결 상태에서 전원 연결 유무에 따라 mac address가 달라지는 현상

**재연 방법**
정창범 실장 PC에서 현상이 재현됨
1. 전원 연결 O, 무선 연결 : 전원 연결 X, 무선 연결 상태에서 라이선스 인증이 안됨
2. 전원 연결 X, 무선 연결 : 전원 연결 O, 무선 연결 상태에서 라이선스 인증이 안됨

**Comment by vulcan9** [comment]
mac adress 등록시 서버 동작에서 다음과 같은 점이 발견되었습니다.
서버측 로직에서 확인이  필요할것 같습니다.

![라이센스 등록 테스트](https://user-images.githubusercontent.com/5111882/102436831-c1f28f00-405c-11eb-87c9-b4e5a24b29d3.png)

**Comment by onlyeye26** [comment]
1개의 mac address당 1개의 라이선스 정책으로 인해 나온 이슈
해당 정책을 유지하여 여러 버전을 사용하더라도 1개의 라이선스를 사용하도록 할 예정이라 문제되지 않습니다.
따라서 해당 이슈는 close 하겠습니다.
