### ISSUE TITLE
[직지 2.0] 기능 수정 및 개선 요청 사항

### ISSUE THREAD

**Issue by tovsoft** [vulcan9/jikji.editor#210]
1. 직지 바인터 최신 nw 버전 교체
2. 빈프로젝트 만들기 할때, 기본 폴더 루트는 바탕화면으로 지정
3. 템플릿을 가져오면, 페이지 리스트에 섬네일 크기가 왜곡됨(작게 나옴)
4. 미리보기 안됨(뷰어는 뜨지만, 페이지가 나오지 않음)
5. 업로드 목록창(서버 출판 목록창)이 뜨지 않음
6. 프로젝트 닫을 때 변경사항이 자동 저장됨(변경된 사항을 저장할지 말지 물어봐야 함)
7. 새 프로젝트를 저장하지 않고 프로젝트 종료했는데... 저장이 되어 있음

**Comment by vulcan9** [comment]
> 1. 직지 바인터 최신 nw 버전 교체

**적용 예정**

> 2. 빈프로젝트 만들기 할때, 기본 폴더 루트는 바탕화면으로 지정

**적용 예정**

> 3. 템플릿을 가져오면, 페이지 리스트에 섬네일 크기가 왜곡됨(작게 나옴)

**재연 할수 있는 정보가 필요합니다.** 

> 4. 미리보기 안됨(뷰어는 뜨지만, 페이지가 나오지 않음)

**문제 증상은 확인할수 없지만 관련됬을 수도 있는 부분에 수정이 있으니 2.0.1 이상 패치버전에서 다시 테스트해보시고 피드백 바랍니다.**

> 5. 업로드 목록창(서버 출판 목록창)이 뜨지 않음

**서버문제로 현재는 정상작동하는것으로 보입니다.**

> 6. 프로젝트 닫을 때 변경사항이 자동 저장됨(변경된 사항을 저장할지 말지 물어봐야 함)

**저장 파일이 아닌 파일 시스템을 바로 사용하는 구조라 정상적인 동작입니다. 실시간으로 적용됩니다.**

> 7. 새 프로젝트를 저장하지 않고 프로젝트 종료했는데... 저장이 되어 있음

**프로젝트 시작과 동시에 실시간으로 변경사항이 저장됩니다. 정상입니다.**

**Comment by tovsoft** [comment]
새 버전에서 테스트 후 새 이슈 공유하는 걸로 하고,
현 이슈는 닫겠습니다.
