### ISSUE TITLE
[직지 2.0.14] 테스트 결과 공유

### ISSUE THREAD

**Issue by tovsoft** [vulcan9/jikji.editor#211]
1. 미리보기
   - 미리보기가 별도 브라우저로 뜸. 바인더 웹뷰로 뜨도록 하면 좋음
   - 작업중인 페이지는 미리보기 페이지에서 제외됨 : 1페이지 작업 후 2페이지를 새로 생성 후 미리보기 하면, 1페이지만 미리보기가 나옴(2페이지 안 나옴) / 미리보기 닫은 후 3페이지 생성 후 미리보기해도 1페이지만 나옴

2. 새이름이로 저장 메뉴가 필요함

3. 프로젝트 시작시 test 폴더를 바탕화면에 만들고 시작했는데... test 폴더를 바탕화면에서 찾을 수가 없음
![image](https://user-images.githubusercontent.com/38056059/104153293-531f1080-5425-11eb-8336-440d9669f2e3.png)

4. 프로젝트 저장 파일은 어떻게 만들 수 있는지 알 수가 없음.

**Comment by vulcan9** [comment]
>    * 미리보기가 별도 브라우저로 뜸. 바인더 웹뷰로 뜨도록 하면 좋음

    - 현재 바인더 웹버전으로 미리보기 실행되고 있음.
    - 현재 바인더 웹버전 API 실행되고 있음.

>    * 작업중인 페이지는 미리보기 페이지에서 제외됨 : 1페이지 작업 후 2페이지를 새로 생성 후 미리보기 하면, 1페이지만 미리보기가 나옴(2페이지 안 나옴) / 미리보기 닫은 후 3페이지 생성 후 미리보기해도 1페이지만 나옴

    - 재연되지 않음.

> 2. 새이름이로 저장 메뉴가 필요함

    - 작업 예정 (현재 프로젝트로 새 프로젝트 생성)
    - 작업 기간 좀 걸릴것으로 예상됨

> 3. 프로젝트 시작시 test 폴더를 바탕화면에 만들고 시작했는데... test 폴더를 바탕화면에서 찾을 수가 없음

    - 폴더를 만들고 시작했다면 빈 폴더라도 남아 있어야함. (에디터에서는 프로젝트 폴더 지우지 않음.)
    - 사용자가 바탕화면에서 폴더를 지운 경우라면, 이 경우 프로젝트 목록에는 남아있음(정상).
    - 문제가 지속적으로 발생하면 프로젝트를 어떻게 시작했는지 과정을 자세하게 알려주세요

> 4. 프로젝트 저장 파일은 어떻게 만들 수 있는지 알 수가 없음.

    - 아래 네모 참고
![프로젝트 저장파일](https://user-images.githubusercontent.com/5111882/104169360-caaf6880-5442-11eb-89b8-433436f01157.png)

**Comment by tovsoft** [comment]
새 버전에서 테스트 후 새 이슈 공유하는 걸로 하고,
현 이슈는 닫겠습니다.
