### ISSUE TITLE
[검토 요청] 구버전 신규버전 라이선스 인증 충돌 확인 요청

### ISSUE THREAD

**Issue by onlyeye26** [vulcan9/jikji.editor#214]
**이슈 내용**
구버전이 설치되어 있는 상태에서 신버전 설치 및 라이선스 인증을 하게 되면 구 버전 라이선스 인증이 오류가 나서 실행이 되지 않습니다.

**재연 방법**
1. 구버전을 설치합니다.(Jik-ji_0.15.1000-cdbook01 (sdk) / 라이선스 : 2020-0226-PR89-QZ0P-YEFF)
2. 구버전을 실행합니다.
3. 신버전을 설치합니다.(Jik-ji Editor 2.0.14-demo (win x86) / 라이선스 : 2021-0122-PU92-P141-1A83)
4. 신버전을 실행합니다.
5. 구버전을 실행하면 라이선스 인증 오류로 실행되지 않습니다.

**예상 이슈**
라이선스 관리자에 이슈가 있어 보입니다.
구버전을 설치(재연 방법 1)하면 라이선스 관리자의 Mac Address에 인증 정보가 보이는데,
신버전을 설치(재연 방법 3)하면 구버전의 Mac Address의 인증정보가 사라지고 신버전의 Mac Address에 인증정보가 생성됩니다.

**예상 결과**
구버전과 신버전이 함께 설치가 되어 있는 상태에서 두 프로그램이 모두 잘 실행되어야 합니다.

**설치파일 경로**
http://116.120.58.79/web/sales/test/download/Jik-jiEditor2.0.14-demo(winx86).zip
http://116.120.58.79/web/sales/test/download/Jik-ji_0.15.1000-cdbook01(sdk)_천재배포.zip

**Comment by vulcan9** [comment]
#206 라이선스 인증시 이슈 
테스트(재연) 내용 참고

**Comment by onlyeye26** [comment]
1개의 mac address당 1개의 라이선스 정책으로 인해 나온 이슈
해당 정책을 유지하여 여러 버전을 사용하더라도 1개의 라이선스를 사용하도록 할 예정이라 문제되지 않습니다.
따라서 해당 이슈는 close 하겠습니다.
