### ISSUE TITLE
페이지가 존재하지 않습니다.

### ISSUE THREAD

**Issue by vulcan9** [vulcan9/jikji.editor#216]
![페이지가 존재하지 않습니다](https://user-images.githubusercontent.com/5111882/108188624-23b1a100-7153-11eb-87b7-f643a5eaecd5.png)

### 재연

  - 빈프로젝트 생성
  - 템플릿 삽입
  - 뷰어 미리보기 실행
  - "페이지가 존재하지 않습니다." 에러 발생

**Comment by vulcan9** [comment]
**Jik-ji_Editor_2.0.20** 버전(이상)에서 처리(구현) 되었습니다.

### 원인
템플릿이 삽입될때 미리보기  페이지 목록 데이터 갱신이 이루어지지 않아 뷰어에서 참조하는  페이지 리스트 정보가 누락됨

**Comment by onlyeye26** [comment]
확인 완료
