### ISSUE TITLE
변환 후 미리보기시 사이즈가 맞지 않게 나옴

### ISSUE THREAD

**Issue by onlyeye26** [vulcan9/jikji.editor#217]
**이슈 내용**
세로로 긴 PDF를 변환 후 미리보기시 가로로 길게 나오며 사이즈가 맞지 않음

**재연 방법**
1. PDF 변환
2. 미리보기
3. 현상 확인

**Screenshots**
변환시 편집 화면
![이미지 001](https://user-images.githubusercontent.com/20455074/108679869-7bc01d00-7530-11eb-9294-57ca78db642f.png)
미리보기 화면
![이미지 002](https://user-images.githubusercontent.com/20455074/108679918-88dd0c00-7530-11eb-9873-3c3c49699b5a.png)

**Comment by vulcan9** [comment]
## 재연
1. `문서 변환 프로젝트 만들기` 선택
2. 프로젝트 폴더 선택 후 `PDF 문서 변환` 선택
3. 세로가 긴 페이지 비율의 pdf 문서 선택 후 변환
4. `뷰어 미리보기` 메뉴 선택하여 미리보기 실행

## 문제
위 이미지와 같이 뷰어(가로형)와 페이지(세로형)의 가로/세로 비율이 상반되게 나타남

**Comment by vulcan9** [comment]
### 원인

- 미리보기할때 공통으로 사용되는 page html 파일에 다음 이미지와 같이 meta 태그가 작성되어져 있어야 뷰어에서 페이지 Iframe의 크기를 정상적으로 설정할 수 있다.

![20210310_140117](https://user-images.githubusercontent.com/5111882/110578966-28450480-81a9-11eb-90c0-682f56a13ba5.png)

- 문서 크기(paper size)가 변경되었어도  이전 문서 크기로 meta 태그 내용이 작성되어져 있다.

### 해결
- 문서 크기가 변경될때 meta 태그 내용을 업데이트해 주어야 한다.
- **2.0.23** 버전(이상)에서 처리(구현) 되었습니다.

**Comment by onlyeye26** [comment]
확인 완료되었습니다.
