### ISSUE TITLE
롤오버 이미지 깜빡거림 현상

### ISSUE THREAD

**Issue by vulcan9** [vulcan9/jikji.editor#218]
이미지로 롤오버튼을 만들면 실제 동작에서 마우스 롤오버를 반복할때마다 이미지 깜빡거림 현상이 나타남.
- 저작도구의 `Chache 이미지 사용 옵션`을 사용하지 않을 경우 심하게 나타남

![image](https://user-images.githubusercontent.com/5111882/112121538-b3d78000-8c02-11eb-8048-ba6d517d65f9.png)

- 개발자 도구에서 `Disable cache` 옵션을 활성화 한 경우 깜빡임 현상 잘 나타남

![image](https://user-images.githubusercontent.com/5111882/112121730-e71a0f00-8c02-11eb-9408-52c8333b9625.png)

**Comment by vulcan9** [comment]
### 원인
마우스 over, leave 할때마다 이미지를 로드하는 시간으로 인해 깜빡임 현상 발생

**Comment by vulcan9** [comment]
## Jik-ji_Editor_2.0.30

* #218 롤오버 이미지 깜빡거림 현상 제거
  - cache 이미지 프리로딩
  - transition 삭제 (이미지 지글거림 현상)

**Comment by onlyeye26** [comment]
확인 완료
