### ISSUE TITLE
썸네일 미리보기 이미지가 페이지와 다름

### ISSUE THREAD

**Issue by vulcan9** [vulcan9/jikji.editor#219]
해당 페이지의 내용이 있음에도 왼쪽 리스트에 내용이 아예 나오지 않거나 배경 이미지만 나오는 등의 현상이 있습니다.  
이 경우 출판 후에도 썸네일 이미지가 나오지 않습니다. 

![image](https://user-images.githubusercontent.com/5111882/110740631-b935e180-8276-11eb-8da4-def11a174165.png)

**Comment by vulcan9** [comment]
### jik2 버전에서 캡쳐 방법이 변경됨

#### jik1 버전의 캡쳐 방식
1. 배경이미지 (master) 썸네일 생성
2. 편집 내용 화면 캡쳐 (투명 배경 이미지)
3. 위 두개의 이미지를 합성
4. 리스트에 보여줄때는 1번 이미지 위에 2번 이미지를 동시에 보여줌

#### jik2 버전의 캡쳐 방식
1. background 프로세스에서 페이지를 직접 로드하여 랜더링된 페이지를 캡쳐 (배경 불투명)
2. 썸네일 생성
4. 리스트에 보여줄때는 2번 이미지를 보여줌

### 원인
jik1 버전에서 생성된 리소스로 리스트에 이미지를 보여주는 과정에 추가 작업이 필요합니다.
jik2 버전에서 보여줄수 있는 썸네일을 별도로 생성해 주어야 합니다.

**Comment by vulcan9** [comment]
### 해결
* 전체 페이지에 대한 썸네일을 다시 갱신해 주는 작업이 필요합니다.  
* 페이지가 많을수록 시간이 많이 걸리는 작업이므로 해당 작업은 background로 진행합니다.

전체 페이지 이미지를 갱신하는 버튼을 누릅니다.
![image](https://user-images.githubusercontent.com/5111882/110741935-d2d82880-8278-11eb-869e-3fbd2d2205c9.png)

작업 진행 상태가 표시되고 취소버튼으로 작업을 취소할 수 있습니다.
작업 진행중 다른 작업을 계속 할 수있습니다.
![image](https://user-images.githubusercontent.com/5111882/110741893-c358df80-8278-11eb-852b-31cf54281b9d.png)

개별 페이지만 이미지를 갱신할 수 있습니다.
![image](https://user-images.githubusercontent.com/5111882/110741860-b89e4a80-8278-11eb-8e56-c5169219022f.png)


**2.0.23** 버전(이상)에서 처리(구현) 되었습니다.

## Jik-ji_Editor_2.0.23
* 썸네일 전체 새로 캡쳐하기
  - 개별 썸네일 생성에도 공통으로 사용
  - 캡쳐 비동기 실행 (background 실행)
  - 캡쳐 중지 기능
* 캡쳐 후 출판용 썸네일 이미지를 생성하지 않음을 기본값으로 변경함
* 페이지 단위 캡쳐 기능 추가
* 닫기버튼 눌렀을때 썸네일 갱신 과정 종료

**Comment by onlyeye26** [comment]
확인 완료
