### ISSUE TITLE
썸네일 목록 안나타남, screen 스크롤 위치 틀어짐

### ISSUE THREAD

**Issue by vulcan9** [vulcan9/jikji.editor#220]
### 재연

![image](https://user-images.githubusercontent.com/5111882/110881438-b644fa80-8323-11eb-9470-4c17b7ae989b.png)

1. 프로젝트 열기 (윈도우 창 크기 작게 조절)
2. `외부파일 설정`  화면 띄우기
3. 윈도우 창 최대화
4. `외부파일 설정`  화면 닫기
5. 다음 과 같은 현상 발생함
    - 썸네일 목록 안나타남
    - 화면 스크롤 위치 틀어짐
6. 창크기를 조절하면 정상적으로 되돌아옴

`외부파일 설정`  화면과 같이 화면 전체를 덮는 메뉴 (`객체 속성` 화면)에서도 같은 현상이 나타남

**Comment by vulcan9** [comment]
### 원인
  - 화면 전체를 덮는 화면 (`$import` 팝업창)을 open 한 경우 퍼포먼스 향상을 위해 팝업창 뒷 화면은 랜더링하지 않도록 되어 있음
      ```
        // RootController
        // 랜더링 퍼포먼스 위해 application 잠시 꺼두기
        var unwatch_power = $scope.$watch(function(){
            return $applications.power;
        }, function(){
            $scope.applicationPower = $applications.power;
        });
      ```
  - 이 상황에서 창 크기를 조절했을때 뒷 화면은 창 크기 조절 이벤트 (resize)를 받지 못함
  - 팝업창을 닫았을때 뒷 화면은 resize 이전 상태로 화면을 랜더링 함.
  - 따라서 썸네일 및 화면 스크롤 위치가 창 사이즈와 부자연스럽게 보여짐
  
### 해결
  - 전체 팝업 창이 닫힐때 창 썸네일, screen 리사이즈 로직 실행할 수 있도록 개선함.

**2.0.27** 버전(이상)에서 처리(구현) 되었습니다.

**Comment by onlyeye26** [comment]
확인 완료
