### ISSUE TITLE
비디오, 오디오, 이미지 파일 삽입시 속성 미리보기에 에러 화면

### ISSUE THREAD

**Issue by onlyeye26** [vulcan9/jikji.editor#221]
**이슈 내용**
비디오, 오디오 파일 삽입시 속성 미리보기에 에러 화면이 뜸
에러 메시지 : MEDIA_ERR_SRC_NOT_SUPPORTED
                      The media could not be loaded. either because the server or network failed or because the format is not supported.
이후 비디오, 오디오 선택을 해지하고 다시 객체를 선택하면 정상으로 돌아옴
(추가) 이미지 삽입시에도 최초에는 이미지가 보이지 않고, 크기 조절하면 이미지가 나타남

**재연 방법**
1. 비디오나 오디오 삽입
2. 속성-기본 설정에 에러 메시지 노출
3. 비디오나 오디오 선택 해제
4. 비디오나 오디오 선택
5. 속성-기본 설정에 정상적으로 미리보기가 됨
(추가)
1. 이미지 삽입
2. 이미지가 보이지 않는 현상 확인
3. 크기 조절
4. 이미지가 나타남

**Screenshots**
![이미지 001](https://user-images.githubusercontent.com/20455074/110894760-c79a0100-833b-11eb-91db-7a6fd580daba.png)

**Comment by onlyeye26** [comment]
이미지 관련 내용 추가

**Comment by vulcan9** [comment]
### 원인
 - `document 삭제에 시간이 너무 오래 걸림 현상` 수정중 side effect 발생함.
 - asset 파일 작업 이전에 데이터가 먼저 변경되어 새로운 asset을 로드하는 시점에 해당 asset을 로드 할 수 없음.

### 해결
  - asset 파일 작업 종료 후 데이터 업데이트 되도록 수정함

**2.0.27** 버전(이상)에서 처리(구현) 되었습니다.

**Comment by onlyeye26** [comment]
확인 완료
