### ISSUE TITLE
텍스트 박스의 속성에서 스타일 노출 오류

### ISSUE THREAD

**Issue by onlyeye26** [vulcan9/jikji.editor#223]
**이슈 내용**
텍스트 박스가 선택된 상태에서 레이아웃을 조정하고 나서 다시 속성창으로 돌아오면 스타일 편집 부분이 제대로 노출되지 않음

**재연 방법**
1. 텍스트 박스 선택('속성-스타일편집'이 정상적으로 나옴)
2. 레이아웃에서 크기 조절
3. 속성창으로 돌아오면 스타일편집이 잘 안나옴
4. 텍스트 박스 선택을 해제 후 다시 선택하면 정상 노출

**Screenshots**
![20210316_152421_319](https://user-images.githubusercontent.com/20455074/111399803-773eec80-8709-11eb-8f94-3cae01697a9e.jpg)

**Comment by vulcan9** [comment]
### 원인
- 스타일 편집창이 뜰때 (초기화) 스타일 표시 대상은 포커싱이 있는 텍스트 박스임
- 다른 속성창이 뜨고 input box로 속성값을 수정하면 포커싱이 input 박스로 바뀜
- 다시 스타일 편집창을 띄울때 스타일 표시 대상은 텍스트 박스가 아님 (포커싱이 없음)

### 해결
- 스타일 편집창이 뜰때 포커싱을 해당 텍스트 박스에 다시 설정해 주어야함

**Comment by vulcan9** [comment]
## Jik-ji_Editor_2.0.28
* (fixed) 텍스트 박스의 속성에서 스타일 노출 오류
  - 속성창 이동시 텍스트 박스 포커싱이 다른 input 박스로 바뀌게되면 스타일을 표시할 객체를 찾지 못하는 현상이 발생함

**Comment by onlyeye26** [comment]
확인 완료

**Comment by vulcan9** [comment]
#271  이슈로 인해 `jjRichTextEditor`에서 focus 처리함
