### ISSUE TITLE
페이지 이동 이벤트 오류

### ISSUE THREAD

**Issue by onlyeye26** [vulcan9/jikji.editor#224]
**이슈 내용**
이전 페이지 이동과 다음 페이지 이동 이벤트가 2페이지씩 넘어감

**재연 방법**
1. 6개의 페이지를 삽입
2. 3페이지에 이미지를 삽입해서 이전 페이지 이동 이벤트 적용
3. 4페이지에 이미지를 삽입해서 다음 페이지 이동 이벤트 적용
4. 출판해서 2페이지씩 이동하는 현상 확인

**Comment by vulcan9** [comment]
### 원인
(테스트 뷰어 버전) jjviewer-0.3.17-static

- 이동할 페이지를 미리 계산하여 뷰어 API `GO_PAGE_LOAD` api를 사용하여 페이지 이동함
- 이동할 페이지를 미리 계산할때  단면, 양면 모드 구별하지 않고 페이지 넘김 단위가 2로 고정되어져 있음

### 해결
- 이전 페이지 이동 : `GO_PAGE_PREVIOUS` 뷰어 api 사용
- 다음 페이지 이동 : `GO_PAGE_NEXT` 뷰어 api 사용
- 특정 페이지 이동 : `GO_PAGE_LOAD` 뷰어 api 사용

**Comment by vulcan9** [comment]
## Jik-ji_Editor_2.0.28
* (fixed) 페이지 이동 이벤트 오류
  - 단면, 양면 모드 구별하지 않고 페이지 넘김 단위가 2로 고정되어져 있음
  - 페이지 계산하지 않고 뷰어 API `GO_PAGE_PREVIOUS`, `GO_PAGE_NEXT` api를 호출하도록 수정함

**Comment by onlyeye26** [comment]
확인 완료
