### ISSUE TITLE
이벤트창 리스트 선택 상자에 리스트가 더 많이 노출시킬 수 있게...

### ISSUE THREAD

**Issue by vulcan9** [vulcan9/jikji.editor#225]
이벤트 동작 설정에서 오브젝트 리스트가 보일 때 해당 리스트의 상하가 더 길어져서 리스트가 더 많이 보일 수 있도록 수정

![image](https://user-images.githubusercontent.com/5111882/112128168-7cb89d00-8c09-11eb-80d4-5b7a7a32a54b.png)

**Comment by vulcan9** [comment]
### 해결
이벤트 창의 크기가 변하면 리스트 선택 박스의 크기가 자동으로 늘어나도록 수정
![image](https://user-images.githubusercontent.com/5111882/112128461-cdc89100-8c09-11eb-92f7-1354d9e80e40.png)

**2.0.29** 버전(이상)에서 처리(구현) 되었습니다.

**Comment by onlyeye26** [comment]
확인 완료
