### ISSUE TITLE
인풋 박스 속성에 행간 조절 추가

### ISSUE THREAD

**Issue by vulcan9** [vulcan9/jikji.editor#226]
1. 텍스트 입력박스를 삽입한다
2.  설정에서 `줄바꿈 허용` 옵션을 체크한다.
3. 행간을 조절할 수 없다.

![image](https://user-images.githubusercontent.com/5111882/112129049-57785e80-8c0a-11eb-879a-7f457fcad37a.png)

**Comment by vulcan9** [comment]
## Jik-ji_Editor_2.0.29
* input element 인풋 박스 속성에 행간 조절 스타일 추가
  - (줄바꿈 허용 옵션일때) 문단스타일 > 행간 활성화

![image](https://user-images.githubusercontent.com/5111882/112129468-cb1a6b80-8c0a-11eb-98a8-250f46090263.png)

**Comment by onlyeye26** [comment]
확인 완료
