### ISSUE TITLE
레이어에서 더블클릭 해서  이름 수정시 가로로 스크롤이 이동함

### ISSUE THREAD

**Issue by vulcan9** [vulcan9/jikji.editor#227]
1. 레이어 창에서 이름을 수정하기 위해 더블클릭한 경우 
2. 수평 스크롤이 자동으로 움직여 
3. 수정 완료 후 스크롤을 항상 다시 움직여 줘야한다.

![image](https://user-images.githubusercontent.com/5111882/112129691-03ba4500-8c0b-11eb-951c-c5cb7be17d95.png)

**Comment by vulcan9** [comment]
## Jik-ji_Editor_2.0.29
* 레이어에서 더블클릭 해서  이름 수정시 가로로 스크롤이 이동함
  - input 박스 auto-scroll 방지

**Comment by onlyeye26** [comment]
확인 완료

**Comment by onlyeye26** [comment]
확인 완료
