### ISSUE TITLE
직지 업데이트 이후 디자인이 깨지는 현상

### ISSUE THREAD

**Issue by onlyeye26** [vulcan9/jikji.editor#228]
**이슈 내용**
2.0.30 버전 업데이트 후 기존에 제작했던 컴포넌트와 템플릿의 디자인이 미리보기시 적용되지 않습니다.
2.0.27 사용했을 때에는 해당 현상이 없었습니다.

**Screenshots**
2.0.27버전에서 컴포넌트 삽입했을 경우 : 컨트롤러의 이미지가 잘 적용되어 있음
![20210324_141401_319](https://user-images.githubusercontent.com/20455074/112260032-93fc9680-8cac-11eb-879c-328737027204.jpg)

2.0.30버전에서 컴포넌트 삽입했을 경우 : 컨트롤러의 이미지가 깨짐
![20210324_141305_124](https://user-images.githubusercontent.com/20455074/112259522-cce83b80-8cab-11eb-8c8d-93a995d1c48d.jpg)

**Comment by vulcan9** [comment]
### 문제
컨트롤러(컴포넌트)를 화면에 삽입함.

- 정상적으로 표시된 모습
![20210324_143753_875](https://user-images.githubusercontent.com/5111882/112261245-cf986000-8cae-11eb-8ac4-aaebbc6fb3bd.jpg)

- `2.0.30`에서 나타나는 모습 (디자인 적용 안됨)
![20210324_143817_261](https://user-images.githubusercontent.com/5111882/112261335-01a9c200-8caf-11eb-9969-c823d249ab72.jpg)

**Comment by vulcan9** [comment]
### 원인
롤오버 이미지 깜빡거림 현상 (#218) 문제 해결 과정에서 다음과 같은 side effect 발생함
- `over`, `down` 이미지를 최초 한번만 설정함
- 런타임에  `~api.source()` API 스크립트에 의해 이미지 소스가 동적으로 변경되는 경우는 롤오버 코드에 반영되지 않음

### 해결
런타임에 이미지 경로 및 스타일 속성이 동적으로 변할때 롤오버 설정을 갱신해줌
**2.0.31** 버전(이상)에서 처리(구현) 되었습니다.

**Comment by onlyeye26** [comment]
확인 완료
