### ISSUE TITLE
미리보기에서 비디오 전체화면 기능 사용시 틀어지는 현상

### ISSUE THREAD

**Issue by onlyeye26** [vulcan9/jikji.editor#229]
**이슈 내용**
미리보기의 비디오 컨트롤러의 전체화면 기능 사용시 컨트롤러 위치가 틀어짐
이전버전(2.0.31)에서는 정상적으로 나옴

**Screenshots**
2.0.31 버전 : 정상
![20210326_151326_453](https://user-images.githubusercontent.com/20455074/112591906-69dfdb80-8e48-11eb-9ccb-fb3b896503d0.jpg)

2.1.0 버전 : 컨트롤러 위치가 틀어짐
![20210326_151311_269](https://user-images.githubusercontent.com/20455074/112591940-76643400-8e48-11eb-80db-5aa69fe9ca34.jpg)

** 테스트에 사용한 jjt 파일 전달 가능

**Comment by vulcan9** [comment]
특정 PC에서만 나타남

**Comment by kenny14** [comment]
이슈 내용
모바일의 경우 전체화면 후 기기 회전을 통해 resize 가 될수 있는데
컨트롤러의 정렬이 아래와 같이 left 픽셀로 고정되어 기기 회전시 중앙 정렬이 되지 않는 현상이 있습니다.

![비디오_컨트롤러_정렬](https://user-images.githubusercontent.com/7077980/123924785-412a2d80-d9c5-11eb-9f18-8d31a164d7f1.png)

- 모바일 기본
![photo_2021-06-30 17 08 38](https://user-images.githubusercontent.com/7077980/123925388-d4636300-d9c5-11eb-9988-d2e7d1be865d.jpeg)

- 모바일 가로 회전시
![photo_2021-06-30 17 07 42](https://user-images.githubusercontent.com/7077980/123925262-b39b0d80-d9c5-11eb-8bab-5d26488f8490.jpeg)

**Comment by vulcan9** [comment]
### 재연

1. 미리보기 실행 (크롬 브라우저)
2. 디버거에서 모바일 모드로 변경
3. 페이지에서 비디오 컨트롤러의 fullscreen 버튼 클릭
4. 디버거에서 Device 회전 시킴
5. 리사이징된 화면 크기로 다시 위치 계산되지 않음

현상 확인됨

**Comment by vulcan9** [comment]
## 샘플 파일에 적용

### 1. 비디오 컨트롤 요소 초기화 코드 수정
`initialize` 이벤트의 편집창에서 다음 부분을 수정합니다.
![image](https://user-images.githubusercontent.com/5111882/125426944-3ade260c-2687-4f01-8742-cb6b994a2663.png)

#### 수정 전
![image](https://user-images.githubusercontent.com/5111882/125427642-74f86844-e4e8-481a-a7b6-b3c07489d060.png)

#### 수정 후
![image](https://user-images.githubusercontent.com/5111882/125428172-88e97d1d-3c43-46c1-a898-2605e2ee5e35.png)

### 2. 비디오 컨트롤 요소의 layout 수정
컨트롤러 ("컨트롤 그룹" 요소)의 중앙 위치를 결정하는 컨테이너인 "비디오 컨트롤" 요소의 layout 설정을 변경합니다.

#### 수정 전
너비 `1280px`에 대한 중앙정렬로 설정되어 있습니다.
![image](https://user-images.githubusercontent.com/5111882/125429336-cf315936-e47c-4d06-a14f-1cb8ca474555.png)

#### 수정 후
양쪽 맞춤으로 수정해주어야 중앙 정렬을 위한 기준 크기가 동적으로 변경됩니다.  
너비값은 비활성화 됩니다.
![image](https://user-images.githubusercontent.com/5111882/125429810-3e6a8d43-4c04-4e73-afdf-bedd2587e374.png)
