### ISSUE TITLE
기본 이미지와 오버 이미지가 함께 보이는 현상

### ISSUE THREAD

**Issue by onlyeye26** [vulcan9/jikji.editor#231]
**이슈 내용**
기본 이미지와 오버 이미지를 넣은 경우 두 이미지가 한꺼번에 보이는 현상

**재연 방법**
1. 이미지 아이템을 삽입합니다.
2. 오버 이미지를 적용합니다.
3. 미리보기 혹은 출판하여 현상을 확입합니다.

**Screenshots**
![20210329_105015_554](https://user-images.githubusercontent.com/20455074/112777360-fffc4780-907c-11eb-8c99-6d8750fb8a5e.jpg)

**Additional context**
27버전부터 발생하는 것으로 보입니다.
진행중인 작업을 중단하고 해당 현상이 개선된 업데이트 이후 작업을 해야 할지,
작업은 그대로 진행하고 추후 업데이트를 하면 개선이 되는 것인지 확인 부탁드립니다.

**Comment by vulcan9** [comment]
### 원인
* (#218) 롤오버 이미지 깜빡거림 현상 해결중 프리로드한 이미지가 표시되고 있었음

### 해결
**2.1.1** 버전(이상)에서 처리(구현) 되었습니다.

**Comment by onlyeye26** [comment]
확인 완료
