### ISSUE TITLE
컴포넌트 내 이미지 충돌 및 손실 현상

### ISSUE THREAD

**Issue by onlyeye26** [vulcan9/jikji.editor#232]
**이슈 내용**
컴포넌트를 등록 / 삽입시 일부 이미지가 충돌되면서 사라지는 현상

**재연 방법**
1. 비디오 컨트롤러, 오디오 컴포넌트 가져오기
2. 비디오 컨트롤러를 페이지에 삽입
3. 비디오 컨트롤러 내 영상 사이즈 조절
4. 사이즈 조절한 버전의 비디오 컨트롤러를 등록 및 내보내기(테스트시 test라는 이름으로 등록 및 내보내기 함)
5. 등록되어 있는 test 컴포넌트 삭제
6. jjc로 내보내기 되어 있는 test 컴포넌트 가져오기
7. 오디오 컴포넌트를 페이지에 삽입
8. 에러 메시지가 나오고 이미지 손실

**Screenshots**
![이미지 007](https://user-images.githubusercontent.com/20455074/114114764-7a9a5200-991c-11eb-8662-2ef18bba55e4.png)

**예상되는 원인**
컴포넌트 간 동일한 UID의 이미지가 사용이 되면서 충돌이 일어나 이미지가 손실되는 것으로 예상됨

**Comment by vulcan9** [comment]
### 재연

![image](https://user-images.githubusercontent.com/5111882/115554343-514ccf00-a2e9-11eb-8c27-8c133d05a36a.png)

1. 분류안됨 카테고리에 있는 컴포넌트중 하나를 목록에서 삭제 (`test` 컴포넌트)
2. 나머지 목록중 컴포넌트 하나를 페이지에 삽입
3. 에러 발생

### 원인

1. 컴포넌트를 제거할때 삭제할 파일 경로를 넘겨줌
    - 컴포넌트 (카테고리)폴더 절대 경로
    - 데이터 파일 이름
    - 썸네일 이미지 파일 이름
    - 컴포넌트 에셋 폴더 이름
2. 컴포넌트의 썸네일이 지정되지 않은 경우 (썸네일 이미지 파일 이름 = `''`)이 전달됨
3. 썸네일 파일 경로가 컴포넌트 폴더 절대 경로와 같아짐
    ```
    썸네일 파일 경로 = 컴포넌트 (카테고리)폴더 절대 경로 + 썸네일 이미지 파일 이름
    ```
4. 컴포넌트 폴더가 삭제되어 카테고리내 모든 컴포넌트가 함께 삭제됨

### 문제 발생
컴포넌트 등록시 썸네일 이미지를 지정하지 않은 컴포넌트를 삭제하면
- 같은 카테고리 내 모든 컴포넌트에 대해서, 또는 카테고리가 지정되지 않은경우 모든 user 컴포넌트에 대해 서 삽입시 에러 발생함
- app 재실행시 카테고리와 카테고리내 컴포넌트가 모두 사라짐

### 해결
삭제할 파일 이름이 지정되지 않은 경우 예외 처리 함

**Comment by vulcan9** [comment]
**2.1.4** 버전(이상)에서 처리(구현) 되었습니다.

**Comment by onlyeye26** [comment]
4. 29 확인 완료
