### ISSUE TITLE
텍스트 입력박스에 한글 입력시 마지막글자 사라짐 현상

### ISSUE THREAD

**Issue by kenny14** [vulcan9/jikji.editor#242]
**이슈 내용**
텍스트 입력박스에 한글 입력시 마지막글자가 사라지는 현상이 있습니다.

**재연 방법**
재연 방법을 단계별로 기술합니다.
1. 텍스트 입력박스에 한글 입력
2. 입력후 100ms 정도 이후 글자 사라짐
[http://112.217.210.162:8080/dev/inputTest/OPS/page-1.html](http://112.217.210.162:8080/dev/inputTest/OPS/page-1.html)

**실행 환경**
 - Browser : chrome(사라짐), safari(정상)
 - Version : 최신버전

**Additional context**
[Angular 한글 입력 이슈](https://gogomalibu.tistory.com/151)

**Comment by vulcan9** [comment]
직지 저작툴  및 출판된 epub 결과물에서는 angularJS를 사용합니다. (not angular)

#### 문제 발생 버전
```
Jik-ji_Editor_2.1.22 이하에서 발생
사용중인 angularJS 버전 : AngularJS v1.6.4
```

#### 관련 angularJS 이슈
https://github.com/angular/angular.js/issues/6656
https://github.com/angular/angular.js/issues/6058

#### 버전 업데이트
```
Jik-ji_Editor_2.1.23 이후 버전 업데이트함
업데이트 angularJS 버전 : AngularJS v1.8.2
```

#### 출판된 epub 업데이트 방법
epub에 적용할 업데이트 (AngularJS v1.8.2) 버전 다운로드 : [epub lib.zip](https://github.com/vulcan9/jikji.editor/files/6928050/epub.lib.zip)
이미 출판된 epub 파일에서 문제 해결을 위해 다음 위치에 angularJS 버전을 덮어쓰기 합니다.
```
epub 파일내 라이브러리 위치
/OPS/js/lib/[angularJS 폴더]
```

#### 저작툴 업데이트
`Jik-ji_Editor_2.1.23` 버전으로 업데이트 후 출판합니다.

---
**2.1.23** 버전(이상)에서 처리(구현) 되었습니다.
