### ISSUE TITLE
[확인 요청] 싱크 컴포넌트 2페이지 연속 사용시 충돌 현상

### ISSUE THREAD

**Issue by onlyeye26** [vulcan9/jikji.editor#243]
**이슈 내용**
싱크 기능을 구현한 컴포넌트를 2페이지 연속 사용시 로컬 바인더 구조 및 웹에서 싱크 js를 불러오지 못하는 현상

**재연 방법**
재연 URL : http://112.217.210.162:8080/sales/test/pms_1/viewer/contents/index.html?contentInformationURL=../../resource/contents/lesson06&page=1

**테스트 결과**
싱크 페이지 사이에 다른 페이지를 삽입하면 해당 현상이 없습니다.

※ 관련 jik2 파일 및 사용한 컴포넌트는 메일로 전송해 드리겠습니다.(사용된 컴포넌트는 2번째 '단원의 첫걸음' 컴포넌트입니다.)

**Comment by vulcan9** [comment]
## 문제 재연
페이지 로드중 다음 alert 창이 나타나지 않아야 한다.

![image](https://user-images.githubusercontent.com/5111882/128476274-a5383340-86e7-4971-b152-438918dbd5ba.png)

**Comment by vulcan9** [comment]
## 디버깅 1
+ alert 창을 호출하는 곳은 `element의 initialize 이벤트` 사용자 스크립트이다
+ 코드에서 체크하고 있는 부분은 자막 데이터 유무인데
```
var captions = window.$captionData ? window.$captionData[captionName] : null;
```

![image](https://user-images.githubusercontent.com/5111882/128476538-bfc1b32c-8a02-40a0-9fa3-b9cc00d48a08.png)

+ `window.$captionData ` 데이터가 생성되는 곳은 외부에서 import한 JS 파일이다.

![image](https://user-images.githubusercontent.com/5111882/128477915-044e96de-d817-40bb-85f3-bfc8be09c4ea.png)

![image](https://user-images.githubusercontent.com/5111882/128477218-a2dbfa2d-f9cf-4c61-aabb-290e31386c4d.png)

### 확인 필요함
> import한 JS 파일이 로드되는 시점과 initialize 이벤트 실행 시점을 비교해본다
`initialize 이벤트`보다 더 늦게 JS 파일이 로드되어 alert 창이 뜰 수도 있지만 가능성은 낮아보임

**Comment by vulcan9** [comment]
## 디버깅 2
네트웍 호출 상황을 비교

### 문제가 발생되지 않을때

![image](https://user-images.githubusercontent.com/5111882/128475592-13810a3c-4fcd-4974-b47d-6cd0e4513abb.png)

+ 뷰어에서 `page-1.html`을 두번 요청하고 있다 (빨간색 박스)
  - 문제상황과 관련은 없지만 모든 리소스가 두번씩 호출되므로 좋지 않음
+ 파란색 박스의 리소스도 두번씩 호출되고 있으나 둘다 사용자 코드에서 실행된 것임
  - 한번은 import된 `interfaceLoad.js` 파일에서 (첫번째 파란 박스) 호출됨
  - 또 한번은 사용자가 로드한 `utils.js`파일에서 (두번째 파란 박스) 호출됨
  - 본 문제와 관련 없어 보임

### 문제가 발생될때

![image](https://user-images.githubusercontent.com/5111882/128476038-1cc22a1f-70c8-4876-aefe-12d742a6bb75.png)

+ `page-2.html` 페이지가 로드됨 (리소스 요청을 함)
+ 문제 발생하지 않을때에도 iframe이 똑같이 생성되지만
![image](https://user-images.githubusercontent.com/5111882/128481805-d3a6fca4-72c1-47da-bad0-0fceee6ca182.png)
+ 문제가 발생 않할때는 리소스 요청이 없으나 문제 발생시에는 `page-2.html`의 리소스들을 요청함
+ 문제가되는 alert 창은 `page-2.html` 에서 발생시키는 것 같음


### 확인 필요함
> `page-2,html` 이 로드되어 세팅되는 도중에 iframe의 src가 재설정 되는것으로 추정됨
(어떤 이유로 뷰어에서 iframe의 src 재설정 타이밍이 달라짐)
따라서 IFrame 내부 HTML DOM은 사라졌지만 실행중인 스크립트에서 다음 순서로 문제가 발생됬을 수 있음

1. `render-page-2.js` 데이터 파일 로드됨
2. iframe (`page-2.html`) 에서 스크립트 동작함
3. iframe src 초기화됨 (iframe document사라짐)
4. 이후 `page-2.html`에서는 DOM 관련된 스크립트 오류 계속 발생됨
5. DOM 이 없으므로 외부에서 import한 JS (`audio_caption.js`) 파일 설정되지 못함 (script 태그 삽입하지 못함)
6. `initialize` 이벤트에 삽입된 사용자 스크립트에서 자막 데이터 찾지 못해 alert 창 띄움

**Comment by vulcan9** [comment]
## 디버깅 1 확인

`window.$captionData` 데이터 로드된 후 `initialize` 이벤트 발생됨을 확인함 (문제 없음)

![image](https://user-images.githubusercontent.com/5111882/128656155-c0f5231f-5971-4c49-9cfc-2b3eeefba237.png)

## 디버깅 2 확인
`page-2.html`에서 자막 찾기 오류 발생 확인됨
`page-2.html`에서 `document.body` 값이 없음

![image](https://user-images.githubusercontent.com/5111882/128656361-2b6558ea-1dd5-4486-a38f-70fbcc6e4e48.png)

## 문제 해결
1. `Jik-ji_Editor_2.1.24` 버전에 `document` 및 `document.body` 값이 없을때 이벤트 실행안하도록 방어 코드 구현함
2. 페이지가 리셋되는 시점에 실행중인 코드를 중지시킬 수 없으므로 비슷한 다른 오류가 계속 발생할 가능성 있음
3. 뷰어에서 사용하지 않는 페이지는 로드 안하도록 하면 좋을것 같음
