### ISSUE TITLE
[검토 요청] 페이지 복사 붙여넣기

### ISSUE THREAD

**Issue by baekeunshin** [vulcan9/jikji.editor#254]
**제안할 기능이 어떤 문제를 해결하기 위한 것인가요? 설명 부탁합니다.**
동일한 레이아웃의 페이지의 경우 전체를 선택하고 새 페이지를 추가해 복사 붙여넣기를 해야 합니다. 

**어떤식으로 문제가 해결됬으면 좋겠습니까?**
페이지 자체가 복사/붙여 넣기가 되었으면 좋겠습니다. ppt처럼 단축기를 사용해서 복사가 가능 하면 좋을 것 같습니다.

![image](https://user-images.githubusercontent.com/107378166/173318244-b6102e78-ea97-4206-bb62-b51dd2a3286e.png)

**Comment by vulcan9** [comment]
#174 [기능요청] 페이지 복사 이슈와 통합합니다.
