### ISSUE TITLE
출판 후 뷰어 미리보기시 크기가 안맞는 현상

### ISSUE THREAD

**Issue by BaeKeun** [vulcan9/jikji.editor#261]
**이슈 내용**
3.0.38 직지 최신 버전에서 출판 후 뷰어 미리보기시 단면, 양면 화면이 틀어지는 현상

**재연 방법**
재연 방법을 단계별로 기술합니다.
1. A4 크기의 pdf를 150% 해상도로 출판
2. 뷰어 미리보기 클릭

**예상 동작**
단면, 양면 모두 크기에 맞게 화면이 나와야 합니다.

**Screenshots**
![image](https://user-images.githubusercontent.com/82875704/177494460-3eb6b79c-7bb8-439b-b020-5f5a5f35564a.png)
![image](https://user-images.githubusercontent.com/82875704/177494518-d8f001e8-b642-4b45-9c6e-dd822eced957.png)
![image](https://user-images.githubusercontent.com/82875704/177494553-555651ba-26d0-4bb9-85a7-f4709f38ff83.png)

**Comment by vulcan9** [comment]
뷰어 이슈로 이동합니다.
[출판 후 뷰어 미리보기시 크기가 안맞는 현상](https://github.com/tovsoft/jikji.viewer/issues/29)

**Comment by vulcan9** [comment]
### 원인 
1. 미리보기에서 페이지 크기가 동적으로 바뀔때 META 태그의 내용이 갱신이 되어야함
2. 이후 meta 태그 내용을 읽어 IFrame의 크기가 바뀐 페이지 크기로 설정됨.
3. 페이지 사이즈가 meta 태그에 동적으로 적용되지 않고 있음

![image](https://user-images.githubusercontent.com/5111882/191085290-d26305a2-0889-4005-ab4f-67469a63ecb3.png)

### 해결
1. 해당 meta 태그 내용을 JS에의해 동적으로 수정하는 방법은 뷰어에서 meta 태그를 통해 사이즈를 참조하는 시점 전,후로 랜덤하게 실행되므로 사용할 수 없음
2. meta 태그를 HTML 파일에서 하드코딩으로 계속 rewrite 해줘야함

**Comment by vulcan9** [comment]
**3.1.26** 버전(이상)에서 처리(구현) 되었습니다.
