### ISSUE TITLE
컴포넌트 캡슐화 목록 중 일부 사라져서 편집 불가

### ISSUE THREAD

**Issue by BaeKeun** [vulcan9/jikji.editor#263]
**이슈 내용**
직지 최신 3.0.38 버전에서 컴포넌트의 캡슐화 목록 중 일부가 사라졌습니다.

**Screenshots**
![image](https://user-images.githubusercontent.com/82875704/179461278-7620bc87-a880-4d70-bf70-b4e751c0c306.png)

**Comment by vulcan9** [comment]
재연가능한 소스가 필요합니다.

**Comment by vulcan9** [comment]
### 원인
* 3.0.26 버전 이후 캡슣화 editor type 중 `list` 타입은 지원이 되지 않습니다.
* data type 형변환 내용도 변경되었습니다.

### 문제 발생
* 그래서 3.0.26 버전 이전에 만들어진 번들 콤포넌트중 `list` type으로 설정된 캡슐화 데이터는 속성창에서 표현되지 않습니다.
* 데이터 형 변환 로직이 바뀌어서 런타임에 캡슐화 데이터를 사용한 콤포넌트 스크립트에서 문제가 발생합니다

### 해결 방법
* `list` 형식의 캡슐화 데이터를 지원해 주어야 합니다.
* 페이지에서 캡슐화 데이터를 받아 사용할때(출판한 후 사용될때) 데이터 형식이 3.0.26 이전 버전일때와 같아야 합니다.
