### ISSUE TITLE
요소 감추기 클릭 시 삭제되는 현상

### ISSUE THREAD

**Issue by BaeKeun** [vulcan9/jikji.editor#264]
**이슈 내용**
직지 최신 3.0.38 버전에서 레이어의 요소 감추기 클릭 시 감추기가 아닌 삭제가 되는 현상

**Screenshots**
![image](https://user-images.githubusercontent.com/82875704/179461993-76b748d4-74ba-4516-bb3a-1a69ef56885a.png)
![image](https://user-images.githubusercontent.com/82875704/179462005-8b775f5a-c45a-4ef9-ac14-cef34be2a59d.png)

**Comment by vulcan9** [comment]
재연 가능한 소스가 필요합니다.

**Comment by vulcan9** [comment]
다음 버전에서 수정되었읍니다.

## Jik-ji_Editor_3.1.22
* 레이어 감추기 버튼 클릭시 레이어 사라짐 현상
  - .hide 클래스가 전체 화면일때 material CSS 설정과 충돌
  - material CSS 미디어 쿼리 : @media (min-width: 1920px)

material CSS 미디어 쿼리에서 hide 클래스 이름을 사용하고 있어 기능이 충돌났었음
