### ISSUE TITLE
직지 튜토리얼 추가, 온라인 사용 설명서 링크 수정

### ISSUE THREAD

**Issue by BaeKeun** [vulcan9/jikji.editor#267]
**제안할 기능이 어떤 문제를 해결하기 위한 것인가요? 설명 부탁합니다.**
직지 튜토리얼 개발, 온라인 사용 설명서 내용 수정으로 인한 직지 내 도움말에서의 메뉴 추가 및 링크 수정

**어떤식으로 문제가 해결됬으면 좋겠습니까?**
![image](https://user-images.githubusercontent.com/82875704/183794785-8a9c90fb-c8fd-4df4-8fa5-974e273239fb.png)

온라인 사용 설명서(pdf) 링크 수정 : https://tovsoft.com/jikji/manual/manual.pdf
직지 튜토리얼 메뉴 추가 : http://tovsoft.com:8080/jikji/tutorial/
※ 직지 튜토리얼의 위치는 온라인 사용 설명서(pdf)와 유튜브 채널의 사이로 요청드립니다.
(도움말 메뉴의 2번째 순서)

**Comment by vulcan9** [comment]
**3.1.8** 버전(이상)에서 처리(구현) 되었습니다.
