### ISSUE TITLE
HTML박스가 삽입된 프로젝트 강제종료 현상

### ISSUE THREAD

**Issue by BaeKeun** [vulcan9/jikji.editor#279]
HTML 박스가 들어간 특정 jik파일에서 강제 종료 현상이 있습니다.
HTML 박스의 편집창을 실행하면 직지가 강제 종료가 됩니다.
![image](https://user-images.githubusercontent.com/82875704/205205963-da8b4e54-ad94-4e00-9488-ea12954c7f05.png)
프로젝트 폴더의 app scale을 약간 높게 조정해서 저장하고 프로젝트를 다시 열어보아도 동일 현상이 있습니다.

같은 소스코드로 다른 프로젝트에서 재연해봤을때는 현상이 없습니다. 
재연 영상과 jik파일을 함께 첨부하여 전달드리겠습니다.
![image](https://user-images.githubusercontent.com/82875704/205206114-e7c0a2c6-6123-405d-b22c-0f3c4c3270a4.png)

**Comment by vulcan9** [comment]
재연 동영상
https://user-images.githubusercontent.com/5111882/205525041-7f51dd80-5230-4445-9f72-0c126abe2493.mp4
재연 소스
[Vardy's On Fire.zip](https://github.com/vulcan9/jikji.editor/files/10149823/Vardy.s.On.Fire.zip)

**Comment by vulcan9** [comment]
### 원인
다음 특수 문자들은 윈도우에서 폴더 이름으로 사용 가능하나 nwJS에서는 로드 에러 발생함.  
(브라우저에서는 정상 동작함)
#### nwJS에서 로드 에러 발생하는 문자
- `'`, `#`, `~`  특수 문자
이번 문제의 경우 프로젝트 폴더명에 single quote `'` 문자가 있는 경우 nwJS에서 로드 에러 발생했음

#### 해당 문자가 문제를 일으키는 경우
- src Atttibute에 경로로 지정되는 경우
  + iframe, img, video, audio
- fontface 정의에 사용된 경우
- CSS url() 함수에 지정되는 경우

### 해결
윈도우 경로 문자열 사용 불가 문자  `\/:*?"<>|`
윈도우 경로 문자열에 포함 가능한 특수문자 중
- 그대로 사용 가능한 문자  `@&=;,+$(){}[]^$-_.!`
- encoding되지 않고 에러 발생하는 문자 `#'~ `

문제가 되는 특수문자를 escape 처리함
```
var url = pathString.replace(/\#|\'|\~/g, escape);
```

### 테스트
`~@&=;,+$(){}[]^$-_.!#'` 이름의 프로젝트 또는 프로젝트 내부 폴더를 생성 후 테스트
```
nw.Window.open(("http://localhost:5301/OPS/~@&=;,+$(){}[]^$-_.!#'/test.html?333"), {new_instance:true})
```
(주의) `new_instance : true` 옵션을 사용하면 문제가 발생되더라도 app이 다운되는 현상은 막을 수 있지만,
- `WIN.capturePage` 캡쳐기능이 동작하지 않음. (process 분리되므로 )
-  `nwJS 0.70.1 버전` (show: false 옵션에서) `WIN.captureScreenshot`  동작하지 않음

**Comment by vulcan9** [comment]
**3.1.39** 버전(이상)에서 처리(구현) 되었습니다.
