### ISSUE TITLE
텍스트 속성중 style, 정렬기능

### ISSUE THREAD

**Issue by Soarts** [vulcan9/jikji.editor#28]
1. 하나의 문장 안에서 특정 단어 기울임이나 진하기 등 설정
2. 텍스트 양쪽 정렬 없음
   - 브라우저마다 다르게 표시될 수 있음. 저작도구에는 표준화된 기능만 들어있는 상태
   - [의견] 그럼에도 적용하는 것을 적극 검토해야 할 수도 있음. (디지털교과서 제작시 중요한 요소)

**Comment by vulcan9** [comment]
1번 내용은 텍스트 에디터(라이브러리)를 적용해야하는 것으로 side effect에 민감한 내용입니다.
2번은 2~3일에 구현 가능하지만 지원되지 않는 브라우저에서에서 보여지는것이 문제네요

**Comment by vulcan9** [comment]
1. 텍스트 에디터가 추가되어 개별 텍스트에 스타일을 지정할 수 있게 되었습니다.
2. 텍스트 에디터에서 양쪽정렬을 지정할 수 있습니다.

**0.11.0** 버전(이상)에서 처리(구현) 되었습니다.
