### ISSUE TITLE
kpub에서 태그 조회가 안되는 현상

### ISSUE THREAD

**Issue by BaeKeun** [vulcan9/jikji.editor#283]
출판 옵션>출판하기 옵션>태그 작성
사용자가 ,뒤에 공백을 붙일경우 서버에 공백이 포함된 태그가 저장되어
태그 조회가 안되는 경우가 발생합니다.
trim으로 앞뒤공백을 제거하여 저장되게 하는 것이 좋을거 같습니다.
ex) BlackPink, 블랙핑크, 블핑

**Comment by vulcan9** [comment]
이 문제는 기 등록된 콘텐츠도 있으니 서버에서 처리해야할 것 같습니다.
일단 직지에도 적용은 했습니다.

**3.1.47** 버전(이상)에서 처리(구현) 되었습니다.
