### ISSUE TITLE
텍스트 박스 속성의 스타일편집 부분 사라지는 현상

### ISSUE THREAD

**Issue by BaeKeun** [vulcan9/jikji.editor#284]
직지에서 작업을 하다가 속성 메뉴를 클릭했을 때 스타일편집 부분이 사라지는 현상이 있습니다.

![image](https://user-images.githubusercontent.com/82875704/210694081-953a4e30-987b-4033-ad65-d9a2f8f1b41e.png)

**Comment by vulcan9** [comment]
## 재연

1. 텍스트 박스 요소가 선택되지 않는 상태에서
2. 속성창에 있는 아무 입력 박스를 클릭하여 입력박스에 포커싱을 준다.
3. 다른 곳을 클릭하여 입력박스의 포커싱을 다시 없앤다.
4.  아무것도 없는 스크린 바닥에서 드래그를 시작하여 텍스트 박스를 선택하면
5. 해당 증상이 나타난다.

**Comment by vulcan9** [comment]
## 원인 & 해결
스타일 메뉴 내용을 갱신할때 다음 로직이 있었음

```
text selection을 검사하여 selection이 없을때
현재 포커싱 노드의 부모가 text element 일때만 스타일 정보를 읽어들여 표시함
```

이 로직을 다음과 같이 수정함
```
selection이 없더라도 선택된 text element의 스타일 정보를 표시하도록 수정함
```

**3.3.13** 버전(이상)에서 처리(구현) 되었습니다.
