### ISSUE TITLE
컴포넌트 스케일 조정 기능 요청

### ISSUE THREAD

**Issue by onlyeye26** [vulcan9/jikji.editor#286]
현재 그룹상자로 묶은 컴포넌트의 경우 가장 상위의 그룹박스 사이즈를 조정하게 되면 
아래와 같이 그룹박스의 영역이 줄어들고 안의 내용은 잘리는 채로 보여지고 있습니다.
![이미지 004](https://user-images.githubusercontent.com/20455074/210725506-e3ea0186-7d8c-4149-9285-4899574d4f87.png)

컴포넌트의 크기 조절 시 안의 오브젝트들도 함께 크기가 조절되게 개발이 가능할지 검토 요청드립니다.
추가 설명이 필요하시면 말씀해주세요.

**Comment by vulcan9** [comment]
다음 두단계로 기능 개선을 진행해야 할것 같습니다.

1. 일단 현재 scale 적용된 표시 방식을 resize 앵커와 동기하 시켜줘야 할듯 합니다.
현재는 resize 앵커 크기에 scale이 적용되어 있지 않습니다.
![image](https://user-images.githubusercontent.com/5111882/214809655-5a1ef5d4-2b07-4bda-b6ea-ac89cbfeeb74.png)

2. 앵커를 드래그하기전 element를 리사이징할지 스케일을 조정할지 옵션을 선택할 수 있도록 분기를 나누어 scale 조정 부분을 구현하면 될듯 합니다.

리사이징 앵커 로직이 굉장히 복잡해서 현재 상태에서 더이상 개발 진행하지 않고 있습니다.
특히 중첩된 그룹내 회전이 들어간 경우 수학적 해석(좌표 변환 & Matrix)이 필요한 부분이라 시간이 많이 걸릴듯 합니다.

**Comment by vulcan9** [comment]
### 발견된 버그 (v3.1.47)
+ 100% 이상 scale 적용된 text element에서 앵커 마우스 드래그 안되는 현상이 있음
+ text element의 입력 박스가 앵커를 가려서  마우스 이벤트가 가려지기 때문임

**Comment by vulcan9** [comment]
### (기능 개선) flip 상태 설정
+ 리상이징 앵커를 드래그해서 마이너스 scale (반전, flip 상태) 설정할 수 있는 기능이 있으면 좋겠음
+ 현재(3.1.47)는 스케일 입력 박스에서만 마이너스 스케일 설정 가능함

**Comment by vulcan9** [comment]
**Jik-ji_Editor_3.2.0** 버전(이상)에서 처리(구현) 되었습니다.

* 마이너스 스케일 (flip) 설정 가능
* 중첩된 그룹내 scale 적용
* 실제 사이즈로 앵커 위치 조정
* 기타 scale, 회전 , 그룹 scale, snap 관련 기능 추가됨

#298 (Jik-ji_Editor_3.2.0 수정 내용 요약 참고)
