### ISSUE TITLE
직지에서 서버에 업로드 시 섬네일 등록 오류

### ISSUE THREAD

**Issue by BaeKeun** [vulcan9/jikji.editor#289]
출판 후 서버에 업로드하기를 했을 때 kpub.co.kr에 노출되는 최신 업로드에서 나오는 목록중에 썸네일이 회색인것은 출판할때 썸네일 등록을 안한것이고, 카탈로그디자인C북처럼 흰색으로 나오는것은 등록했는데 섬네일오류가 난것으로 보입니다.

![image](https://user-images.githubusercontent.com/82875704/215038395-0e3e1e41-75f6-49de-8ab5-2e8daccd8a89.png)

**Comment by vulcan9** [comment]
#292 이슈 통합 합니다.

**Comment by vulcan9** [comment]
서버에 썸네일 정상적으로
