### ISSUE TITLE
출판했을 때 jjbundle의 뷰어 설정이 우선 적용되는 현상

### ISSUE THREAD

**Issue by BaeKeun** [vulcan9/jikji.editor#290]
1. 현재 epub으로 출판했을 때 안의 출판물에는 jjbundle 폴더가 같이 출판 됩니다.
![image](https://user-images.githubusercontent.com/82875704/215046810-e075a0b7-295c-41fe-94af-f2ed2d4def52.png)

2. 단순 epub으로 출판했을 경우에는 jjbundle 폴더가 생성되지 않게 수정되었으면 합니다.

**Comment by vulcan9** [comment]
#287 이슈로 통합합니다.
