### ISSUE TITLE
섬네일을 등록안했을 경우 서버에 업로드가 안되도록 하는 기능

### ISSUE THREAD

**Issue by BaeKeun** [vulcan9/jikji.editor#291]
1. 섬네일을 등록안했을 경우 서버에 업로드 자체가 안되도록 기능이 개선되었으면 좋겠습니다.
2. 섬네일을 등록안한 상태에서 출판을 클릭했을 경우 "섬네일을 등록해주세요" 라는 알림창이 나와 섬네일을 등록하도록 유도하였으면 합니다.

**Comment by vulcan9** [comment]
#292 이슈 통합합니다.

**Comment by vulcan9** [comment]
## Jik-ji_Editor_3.1.51

* 기본 cover 이미지로 첫번째 페이지 썸네일을 사용하도록 개선되었습니다.
