### ISSUE TITLE
섬네일 품질 향상 요청

### ISSUE THREAD

**Issue by onlyeye26** [vulcan9/jikji.editor#296]
현재 직지에서 찍히는 섬네일의 해상도가 낮아 뷰어에서 섬네일 확인이 어렵습니다.
섬네일이 더 좋은 품질로 출판될 수 있도록 수정 부탁드립니다.

**Comment by vulcan9** [comment]
## Quality 및 사이즈 변경
* 50 quality와 100 quality 이미지 사이에 용량 차이가 거의 없음 (늘어나지 않음)
* 캡쳐(편집) 이미지와 master 이미지가 merge 될때 quality에 의한 용량 차이가 상쇄된듯함
* 썸네일 quality 설정이 최종 결과물 용량에 크게 영향을 미치지 않으면 100으로 설정해도 될것 같음
* 아래 용량 차이는 사이즈에 의해 늘어난 용량으로 보면됨
* 썸네일 뽑아낼때 배경(master) 이미지의 패턴이 지정되지 않은 경우
  - 캡쳐이미지와 master 이미지 바로 merge 시킴 (중간 로직 생략함)
  - 생략된 로직이 썸네일 용량에 가장 크게 영향을 줌 (300px 일때 오히려 용량이 더 작음)

|수정 전|수정 후 (300px)|수정 후 (400px 100Q)|수정 후 (400px 50Q)|
|---------------|---------------|---------------|---------------|
|![image](https://github.com/vulcan9/jikji.editor/assets/5111882/af6e7381-de90-4233-a5fb-5094a07cea7c)|![image](https://github.com/vulcan9/jikji.editor/assets/5111882/49e29765-a537-4756-bf2b-86dbd7fd9549)|![image](https://github.com/vulcan9/jikji.editor/assets/5111882/40d9130f-1843-463e-a351-cfbd3afb5a92)|![image](https://github.com/vulcan9/jikji.editor/assets/5111882/71ee06f0-16cb-42a7-97f4-442ecc42add9)|
|![document-197df0e8-2d41-4bc7-b4bd-61a3bac26012](https://github.com/vulcan9/jikji.editor/assets/5111882/f0cb0738-bdd0-43e0-83e9-c45774f944d4)|![document-a079042d-a10b-402f-bf74-f58e6c432f14](https://github.com/vulcan9/jikji.editor/assets/5111882/5203bac8-51ae-4df5-a807-deb5fcf8944d)|![document-33d5d9d3-cbe6-4336-a143-d3b748bc1884](https://github.com/vulcan9/jikji.editor/assets/5111882/e4ded623-2af9-42ae-9d72-686622833077)|![document-7aae1042-742e-4e5d-8222-a1b3c687dd4b](https://github.com/vulcan9/jikji.editor/assets/5111882/05deed1d-e39c-4fcf-9462-117dc9ac3526)|


## 뷰어에 적용했을때 썸네일 표시
* 썸네일 사이즈를 200px 에서  300px, 400px 이내로 크기 제한 범위를 넓힘
* 300px 과 400px은 거의 차이가 없어 보임

![image](https://github.com/vulcan9/jikji.editor/assets/5111882/baa7c29b-c9bf-41cb-995f-96f283660d33)


## 변경 사항
* 썸네일 quality 100으로 설정함
* 썸네일 사이즈 300px로 설정함
* 이미지 merge 로직 수정

**Jik-ji_Editor_3.2.11** 버전(이상)에서 처리(구현) 되었습니다.
